# Generated by Django 4.2.15 on 2024-08-22 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('mismatch_count', models.IntegerField()),
                ('mismatch_percentage', models.FloatField()),
            ],
        ),
    ]
