# Generated by Django 4.2.15 on 2024-08-22 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zipprocessor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
