# Generated by Django 4.2.15 on 2024-08-22 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zipprocessor', '0002_record_last_modified'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvalidImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='record',
            name='invalid_images',
            field=models.ManyToManyField(to='zipprocessor.invalidimage'),
        ),
    ]
