# Generated by Django 4.2.15 on 2024-08-23 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zipprocessor', '0003_invalidimage_record_invalid_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='record',
            name='content_images',
            field=models.ManyToManyField(to='zipprocessor.contentimage'),
        ),
    ]
