# Generated by Django 4.2.15 on 2024-08-24 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zipprocessor', '0004_contentimage_record_content_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='record',
            name='valid_images',
            field=models.ManyToManyField(to='zipprocessor.validimage'),
        ),
    ]
